name: Check
on:
  workflow_dispatch:
    inputs:
      only_deploy:
        description: 'Only deploy'
        default: 'false'
  schedule:
    # Daily at 7AM Pacific / 14:00 UTC
    - cron: '0 14 * * *'

concurrency: 1

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '*'
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        name: Install pnpm
        with:
          version: latest
          run_install: true
      - run: pnpm build
      - uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ./cache # This path must match the path in the `save` step below, otherwise it doesn't work.
          key: dt-cache-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: dt-cache-
          fail-on-cache-miss: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.only_deploy == 'true' }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.only_deploy == 'false' }}
        with:
          repository: DefinitelyTyped/DefinitelyTyped
          path: ./DefinitelyTyped

      - run: |
          mv ./cache ./cacheIn || true
          node dist/main.js check --dt ./DefinitelyTyped --input ./cacheIn --output ./cache --verbose
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.only_deploy == 'false' }}

      - run: node dist/main.js generate-site --input ./cache --output ./rawSite
      - run: cp ./_config.yml rawSite/_config.yml

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@b178f9334b208360999a0a57b523613563698c66 # v1.0.12
        with:
          source: ./rawSite
          destination: ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ./site

      - uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.only_deploy == 'false' }}
        with:
          path: ./cache
          key: dt-cache-${{ github.run_id }}-${{ github.run_attempt }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
