name: Check
on:
  workflow_dispatch:
  schedule:
    # Daily at 16:00 UTC
    - cron: '0 16 * * *'

concurrency: 1

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: true
      - run: pnpm build
      - uses: actions/cache/restore@v3
        with:
          path: ./cacheIn
          key: dt-cache-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: dt-cache-

      - uses: actions/checkout@v4
        with:
          repository: DefinitelyTyped/DefinitelyTyped
          path: ./DefinitelyTyped

      - run: node dist/main.js check --dt ./DefinitelyTyped --input ./cacheIn --output ./cacheOut --verbose

      - run: node dist/main.js generate --input ./cacheOut --output rawSite

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./rawSite
          destination: ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ./cacheOut
          key: dt-cache-${{ github.run_id }}-${{ github.run_attempt }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
